name: minhlong_menu_admin_v3
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  cached_network_image: ^3.3.1
  flutter_animate: ^4.5.0
  intl: ^0.19.0
  readmore: ^3.0.0
  badges: ^3.1.2
  flutter_svg: ^2.0.10+1
  tiengviet: ^1.0.0
  json_annotation: ^4.9.0
  dio: ^5.4.3+1
  logger: ^2.3.0
  shared_preferences: ^2.2.3
  flutter_multi_formatter: ^2.12.8
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  fl_chart: ^0.68.0
  animated_text_kit: ^4.2.2
  flutter_staggered_grid_view: ^0.7.0
  web_socket_channel: ^3.0.0
  device_preview: ^1.2.0
  flutter_bloc: ^8.1.6
  go_router: ^14.2.0
  easy_sidemenu: ^0.6.0
  flutter_screenutil: ^5.9.3
  shimmer: ^3.0.0
  # number_paginator: ^0.4.1
  number_pagination: ^1.0.7
  linear_timer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true




  assets:
    # - images/
    - assets/image/
    - assets/svg/
