# version: '3.9'
networks:
  minhlong_menu_network:
    name: minhlong_menu_network
    driver: bridge

services:
  mysql-container:
    image: mysql:9.0.1
    container_name: mysql-container
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3336:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - minhlong_menu_network

  phpmyadmin-container:
    container_name: phpmyadmin-container
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    depends_on:
      - mysql-container
    environment:
      PMA_HOST: mysql-container
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: Minhlong@123
    networks:
      - minhlong_menu_network

  minhlong-menu:
    build: .
    image: minhlong-menu/app:latest
    container_name: minhlong-menu
    restart: always
    volumes:
      - app:/app
      - ./public:/public
      - ./storage:/storage
    ports:
      - 8000:8000
    networks:
      - minhlong_menu_network

volumes:
  app:
  mysql_data:


